config/routes.rb
Rails.application.routes.draw do
  resources :budget_categories
  resources :transactions
  resources :trips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget_category.rb
class BudgetCategory < ApplicationRecord
  belongs_to :trip
  has_many :transactions
  
  def spent
    update(sum_cache: sum_transactions) if sum_cache.nil?
    sum_cache
  end
  
  def add(amount)
    update!(sum_cache: spent + amount)
  end
  
  def subtract(amount)
    update!(sum_cache: spent - amount)
  end
  
  private
  
  def sum_transactions
    transactions.sum(:amount)
  end
  
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :budget_category

  after_save :increment_budget_spent
  after_destroy :decrement_budget_spent

  private

  def increment_budget_spent
    budget_category.add(amount) 
  end
  
  def decrement_budget_spent
    budget_category.subtract(amount)
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :budget_categories
  has_many :transactions, through: :budget_categories
  
  def complete?
    end_date < Date.current
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/budget_categories_controller.rb
class BudgetCategoriesController < ApplicationController
  before_action :set_budget_category, only: %i[ show edit update destroy ]

  # GET /budget_categories or /budget_categories.json
  def index
    @budget_categories = BudgetCategory.all
  end

  # GET /budget_categories/1 or /budget_categories/1.json
  def show
  end

  # GET /budget_categories/new
  def new
    @budget_category = BudgetCategory.new
  end

  # GET /budget_categories/1/edit
  def edit
  end

  # POST /budget_categories or /budget_categories.json
  def create
    @budget_category = BudgetCategory.new(budget_category_params)

    respond_to do |format|
      if @budget_category.save
        format.html { redirect_to @budget_category, notice: "Budget category was successfully created." }
        format.json { render :show, status: :created, location: @budget_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budget_categories/1 or /budget_categories/1.json
  def update
    respond_to do |format|
      if @budget_category.update(budget_category_params)
        format.html { redirect_to @budget_category, notice: "Budget category was successfully updated." }
        format.json { render :show, status: :ok, location: @budget_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_categories/1 or /budget_categories/1.json
  def destroy
    @budget_category.destroy!

    respond_to do |format|
      format.html { redirect_to budget_categories_path, status: :see_other, notice: "Budget category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget_category
      @budget_category = BudgetCategory.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def budget_category_params
      params.expect(budget_category: [ :name, :budgeted_amount, :trip_id ])
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy!

    respond_to do |format|
      format.html { redirect_to transactions_path, status: :see_other, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.expect(transaction: [ :note, :amount, :trip_id ])
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]

  # GET /trips or /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1 or /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy!

    respond_to do |format|
      format.html { redirect_to trips_path, status: :see_other, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.expect(trip: [ :name, :location, :start_date, :end_date ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budget_categories_helper.rb
module BudgetCategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/budget_categories/_budget_category.html.erb
<div id="<%= dom_id budget_category %>">
  <p>
    <strong>Name:</strong>
    <%= budget_category.name %>
  </p>

  <p>
    <strong>Budgeted amount:</strong>
    <%= budget_category.budgeted_amount %>
  </p>

  <p>
    <strong>Trip:</strong>
    <%= budget_category.trip_id %>
  </p>

</div>

app/views/budget_categories/_form.html.erb
<%= form_with(model: budget_category) do |form| %>
  <% if budget_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget_category.errors.count, "error") %> prohibited this budget_category from being saved:</h2>

      <ul>
        <% budget_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :budgeted_amount, style: "display: block" %>
    <%= form.text_field :budgeted_amount %>
  </div>

  <div>
    <%= form.label :trip_id, style: "display: block" %>
    <%= form.text_field :trip_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budget_categories/edit.html.erb
<% content_for :title, "Editing budget category" %>

<h1>Editing budget category</h1>

<%= render "form", budget_category: @budget_category %>

<br>

<div>
  <%= link_to "Show this budget category", @budget_category %> |
  <%= link_to "Back to budget categories", budget_categories_path %>
</div>

app/views/budget_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Budget categories" %>

<h1>Budget categories</h1>

<div id="budget_categories">
  <% @budget_categories.each do |budget_category| %>
    <%= render budget_category %>
    <p>
      <%= link_to "Show this budget category", budget_category %>
    </p>
  <% end %>
</div>

<%= link_to "New budget category", new_budget_category_path %>

app/views/budget_categories/new.html.erb
<% content_for :title, "New budget category" %>

<h1>New budget category</h1>

<%= render "form", budget_category: @budget_category %>

<br>

<div>
  <%= link_to "Back to budget categories", budget_categories_path %>
</div>

app/views/budget_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budget_category %>

<div>
  <%= link_to "Edit this budget category", edit_budget_category_path(@budget_category) %> |
  <%= link_to "Back to budget categories", budget_categories_path %>

  <%= button_to "Destroy this budget category", @budget_category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tripbuckets" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_field :note %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :trip_id, style: "display: block" %>
    <%= form.text_field :trip_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Note:</strong>
    <%= transaction.note %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  </p>

  <p>
    <strong>Trip:</strong>
    <%= transaction.trip_id %>
  </p>

</div>

app/views/transactions/edit.html.erb
<% content_for :title, "Editing transaction" %>

<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Transactions" %>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>

app/views/transactions/new.html.erb
<% content_for :title, "New transaction" %>

<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>

app/views/trips/_form.html.erb
<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<div id="<%= dom_id trip %>">
  <p>
    <strong>Name:</strong>
    <%= trip.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= trip.location %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= trip.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= trip.end_date %>
  </p>

</div>

app/views/trips/edit.html.erb
<% content_for :title, "Editing trip" %>

<h1>Editing trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Show this trip", @trip %> |
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Trips" %>

<h1>Trips</h1>

<div id="trips">
  <% @trips.each do |trip| %>
    <%= render trip %>
    <p>
      <%= link_to "Show this trip", trip %>
    </p>
  <% end %>
</div>

<%= link_to "New trip", new_trip_path %>

app/views/trips/new.html.erb
<% content_for :title, "New trip" %>

<h1>New trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trip %>

<div>
  <%= link_to "Edit this trip", edit_trip_path(@trip) %> |
  <%= link_to "Back to trips", trips_path %>

  <%= button_to "Destroy this trip", @trip, method: :delete %>
</div>